server:
  port: 19016
  max-http-header-size: 102400
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    # 不要设置过大，如果过大，启动项目会报错：打开文件数过多
    io-threads: 16
    # 阻塞任务线程池, 当执行类似servlet请求阻塞IO操作, undertow会从这个线程池中取得线程
    # 它的值设置取决于系统线程执行任务的阻塞系数，默认值是IO线程数*8
    worker-threads: 256
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可
    buffer-size: 1024
    # 每个区分配的buffer数量 , 所以pool的大小是buffer-size * buffers-per-region
    buffers-per-region: 1024
    # 是否分配的直接内存(NIO直接分配的堆外内存)
    direct-buffers: true
spring:
  application:
    name: sweet-web
  profiles:
    active: prod
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-request-size: 1024MB
      max-file-size: 1024MB
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://${MYSQL_HOST:10.1.10.92}:${MYSQL_PORT:3306}/egrand-cloud-dwork-lyffp?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8&connectTimeout=60000&socketTimeout=30000
          username: ${MYSQL_USERNAME:root}
          password: ${MYSQL_PASSWORD:123456}
          driverClassName: com.mysql.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
    tenant:
      enabled: true
      url: jdbc:mysql://${TENANT_MYSQL_HOST:10.1.10.188}:${TENANT_MYSQL_PORT:3306}/egrand-cloud-ky3h-admin?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
      username: root
      password: ${TENANT_MYSQL_PASSWORD:123456}
      cron: '0 */1 * * * ?'
  wechat:
    cp:
      enable-multi: true
      multi:
        default:
          agentId: 1000006
          corpId: wwe22a938cc608ae5f
          secret: 2tPz2arb2qH6SYGjTv_Wt_MvntYtxVVBtPWoWNNgeLQ
          token: 111
          aesKey: 111
#        zcyj:
#          agentId: 1000010
#          corpId: wwe22a938cc608ae5f
#          secret: ZID0tfN62-m4o7WY5o_kC7T-y1ZMdUi8Nm_jS5SUZCA
#          token: 111
#          aesKey: 111
  rabbitmq:
    enable-multi: true
    multi:
      default:
        virtual-host: /dwork-plus
        # 主机地址，默认localhost
        host: 10.1.10.178
        # 主机端口，默认5672
        port: 5672
        # 访问用户名
        username: wiki
        # 访问密码
        password: wiki2012
        # 是否启用【发布确认】，默认none
        publisher-confirm-type: correlated
        # 是否启用【发布返回】，默认false
        publisher-returns: true
        template:
          mandatory: true
        listener:
          simple:
            # 表示消息确认方式，其有三种配置方式，分别是none、manual和auto；默认auto
            acknowledge-mode: manual
  redis:
    enable-multi: true
    multi:
      default:
        database: 1
        host: 10.1.10.178
        password:
        port: 6364
        timeout: 60000
        lettuce:
          pool:
            max-active: -1
            max-idle: -1
            max-wait: -1
            min-idle: -1
        enable-multi: true
      two:
        database: 1
        host: 10.1.10.178
        port: 6370
        password:
        timeout: 60000
        lettuce:
          pool:
            max-active: -1
            max-idle: -1
            max-wait: -1
            min-idle: -1
  # 配置Elasticsearch bboss
  elasticsearch:
    enableMulti: true
    multi:
      default:
        name: default
        elasticUser: elastic
        elasticPassword: changeme
        elasticsearch:
          rest:
            hostNames: ${ES_HOST:10.1.10.178}:${ES_PORT:9200}
            ##hostNames: 10.1.10.209:9200,10.1.10.210:9200 ##集群地址配置
          dateFormat: yyyy.MM.dd
          timeZone: Asia/Shanghai
          # 在控制台输出脚本调试开关showTemplate,false关闭，true打开，同时log4j至少是info级别
          showTemplate: true
          discoverHost: false
        dslfile:
          # dsl配置文件热加载扫描时间间隔，毫秒为单位，默认5秒扫描一次，<= 0时关闭扫描机制
          refreshInterval: -1
        # es client http连接池配置
        http:
          timeoutConnection: 5000
          timeoutSocket: 5000
          connectionRequestTimeout: 5000
          retryTime: 1
          maxLineLength: -1
          maxHeaderCount: 200
          maxTotal: 400
          defaultMaxPerRoute: 200
          soReuseAddress: false
          soKeepAlive: false
          timeToLive: 3600000
          keepAlive: 3600000
          keystore:
          keyPassword:
          hostnameVerifier:
      spb:
        name: dpra-es
        elasticUser: elastic
        elasticPassword: changeme
        elasticsearch:
          rest:
            hostNames: ${ES_HOST:10.1.10.178}:${ES_PORT:5200}
            ##hostNames: 10.1.10.209:9200,10.1.10.210:9200 ##集群地址配置
          dateFormat: yyyy.MM.dd
          timeZone: Asia/Shanghai
          # 在控制台输出脚本调试开关showTemplate,false关闭，true打开，同时log4j至少是info级别
          showTemplate: true
          discoverHost: false
        dslfile:
          # dsl配置文件热加载扫描时间间隔，毫秒为单位，默认5秒扫描一次，<= 0时关闭扫描机制
          refreshInterval: -1
        # es client http连接池配置
        http:
          timeoutConnection: 5000
          timeoutSocket: 5000
          connectionRequestTimeout: 5000
          retryTime: 1
          maxLineLength: -1
          maxHeaderCount: 200
          maxTotal: 400
          defaultMaxPerRoute: 200
          soReuseAddress: false
          soKeepAlive: false
          timeToLive: 3600000
          keepAlive: 3600000
          keystore:
          keyPassword:
          hostnameVerifier:
      dpraprod:
        name: egd-es
        elasticUser: elastic
        elasticPassword: changeme
        elasticsearch:
          rest:
            hostNames: ${ES_HOST:10.1.10.178}:${ES_PORT:5201}
            ##hostNames: 10.1.10.209:9200,10.1.10.210:9200 ##集群地址配置
          dateFormat: yyyy.MM.dd
          timeZone: Asia/Shanghai
          # 在控制台输出脚本调试开关showTemplate,false关闭，true打开，同时log4j至少是info级别
          showTemplate: true
          discoverHost: false
        dslfile:
          # dsl配置文件热加载扫描时间间隔，毫秒为单位，默认5秒扫描一次，<= 0时关闭扫描机制
          refreshInterval: -1
        # es client http连接池配置
        http:
          timeoutConnection: 5000
          timeoutSocket: 5000
          connectionRequestTimeout: 5000
          retryTime: 1
          maxLineLength: -1
          maxHeaderCount: 200
          maxTotal: 400
          defaultMaxPerRoute: 200
          soReuseAddress: false
          soKeepAlive: false
          timeToLive: 3600000
          keepAlive: 3600000
          keystore:
          keyPassword:
          hostnameVerifier:
mybatis-plus:
  global-config:
    db-config:
      #定义id生成策略
      id-type: auto
  configuration:
    mapUnderscoreToCamelCase: true
  typeAliasesPackage: com.egrand.sweetapi.web.model.entity
  mapper-locations: classpath:mapper/*.xml
